[node]
number = 123456
callsign = "N0CALL"
[security]
internal_networks[] = "127.0.0.1/32"
internal_networks[] = "192.168.1.0/24"
internal_networks[] = "10.0.0.0/8"
internal_networks[] = "172.16.0.0/12"
; internal_networks[] = "::1/128"           ; localhost IPv6
